CREATE TABLE AUD_INVENTARIO(usuario VARCHAR2(30),momento VARCHAR2(30),valor VARCHAR2(50));

CREATE TABLE AUD_EMPLEADO(usuario VARCHAR2(30),momento VARCHAR2(30),valor VARCHAR2(50));

CREATE TABLE AUD_PROVEEDOR(usuario VARCHAR2(30),momento VARCHAR2(30),valor VARCHAR2(50));

CREATE TABLE AUD_PRODUCTO(usuario VARCHAR2(30),momento VARCHAR2(30),valor VARCHAR2(50));

CREATE TABLE AUD_DETALLE_COMPRA(usuario VARCHAR2(30),momento VARCHAR2(30),valor VARCHAR2(50));

CREATE TABLE AUD_DETALLE_FACTURA(usuario VARCHAR2(30),momento VARCHAR2(30),valor VARCHAR2(50));