CREATE SEQUENCE seq_id_cargo
  INCREMENT BY 1
  START WITH 6
  MAXVALUE 99
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE seq_id_detalle
  INCREMENT BY 1
  START WITH 12
  MAXVALUE 99999
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE seq_id_marca
  INCREMENT BY 1
  START WITH 6
  MAXVALUE 999
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE seq_id_producto
  INCREMENT BY 1
  START WITH 6
  MAXVALUE 99999
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE seq_id_categoria
  INCREMENT BY 1
  START WITH 5
  MAXVALUE 999
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE seq_id_inventario
  INCREMENT BY 1
  START WITH 25
  MAXVALUE 99999
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE seq_id_compra
  INCREMENT BY 1
  START WITH 5
  MAXVALUE 99999
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE seq_id_detalleCompra
  INCREMENT BY 1
  START WITH 25
  MAXVALUE 99999
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE seq_id_medio
  INCREMENT BY 1
  START WITH 4
  MAXVALUE 99
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE seq_id_factura
  INCREMENT BY 1
  START WITH 4
  MAXVALUE 99999
  NOCACHE
  NOCYCLE;