CREATE SYNONYM reg_ventas
FOR REGISTRO_VENTASVU;

CREATE SYNONYM inf_empleado
FOR INFORMACION_EMPLEADOSVU;

CREATE SYNONYM cto_proveedor
FOR CONTACTO_PROVEEDORESVU;

CREATE SYNONYM reg_compras
FOR REGISTRO_COMPRASVU;

CREATE SYNONYM num_productos
FOR CANTIDAD_PRODUCTOSVU;

CREATE SYNONYM factura
FOR ENCABEZADO_FACTURA;

CREATE SYNONYM dlle_factura
FOR DETALLE_FACTURA;

CREATE SYNONYM dlle_compra
FOR DETALLE_COMPRA;

CREATE SYNONYM categoria_pdto		
FOR CATEGORIA_PRODUCTO;

CREATE SYNONYM marca_pdto		
FOR MARCA_PRODUCTO;