CREATE TABLE CARGO(
	ID_CARGO		NUMBER(3) NOT NULL,
	CARGO           	VARCHAR2(40),
	SALARIO_BASE            NUMBER(10,2),
	CONSTRAINT Cargo_idCargo_pk PRIMARY KEY (ID_CARGO)
);

CREATE TABLE EMPLEADO(
	ID_EMPLEADO		NUMBER(11) NOT NULL,
        ID_CARGO		NUMBER(3) NOT NULL,    
	NOMBRES         	VARCHAR2(40),
	APELLIDOS       	VARCHAR2(40),
        TELEFONO		NUMBER(14),
        DIRECCION               VARCHAR2(50),
	CONSTRAINT Empleado_IdEmpleado_pk PRIMARY KEY (ID_EMPLEADO),
        CONSTRAINT Cliente_IdCargo_fk FOREIGN KEY (ID_CARGO) REFERENCES CARGO (ID_CARGO)
);

CREATE TABLE TIPO_CLIENTE(
	ID_TIPO		        NUMBER(3) NOT NULL,
	CATEGORIA_CLIENTE	VARCHAR2(50),
	CONSTRAINT TipoClinete_IdTipo_pk PRIMARY KEY (ID_TIPO)	
);

CREATE TABLE CLIENTE(
	IDENTIFICACION		NUMBER(10) NOT NULL,
        ID_TIPO		        NUMBER(3) NOT NULL,
	NOMBRES		        VARCHAR2(40),
	APELLIDOS	        VARCHAR2(40),
	TELEFONO		NUMBER(14),
	CORREO_ELECTRONICO      VARCHAR2(50),
	CONSTRAINT Cliente_Identificacion_pk PRIMARY KEY (IDENTIFICACION),
        CONSTRAINT Cliente_IdTipo_fk FOREIGN KEY (ID_TIPO) REFERENCES TIPO_CLIENTE (ID_TIPO)
);

CREATE TABLE MEDIO_PAGO(
	ID_MEDIO_DEPAGO		NUMBER(2) NOT NULL,
	TIPO_MEDIOPAGO          VARCHAR2(15),
        CONSTRAINT MedioPago_IdMedioDePago_pk PRIMARY KEY(ID_MEDIO_DEPAGO)
);

CREATE TABLE ENCABEZADO_FACTURA(
	ID_FACTURA		NUMBER(15) NOT NULL,
        ID_EMPLEADO		NUMBER(11) NOT NULL,
        IDENTIFICACION		NUMBER(11) NOT NULL,
        ID_MEDIO_DEPAGO		NUMBER(2) NOT NULL,
	FECHA		        DATE,
	CONSTRAINT EnFact_IdFactura_pk PRIMARY KEY (ID_FACTURA),
	CONSTRAINT EnFact_IdEmpleado_fk FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO),
        CONSTRAINT EnFact_Identificacion_fk1 FOREIGN KEY (IDENTIFICACION) REFERENCES CLIENTE (IDENTIFICACION),
        CONSTRAINT EnFact_IdMedio_fk2 FOREIGN KEY (ID_MEDIO_DEPAGO) REFERENCES MEDIO_PAGO (ID_MEDIO_DEPAGO)
);

CREATE TABLE PROVEEDOR(
       ID_PROVEEDOR            NUMBER(10) NOT NULL,
       NOMBRES                 VARCHAR2(40),
       APELLIDOS               VARCHAR2(40),
       TELEFONO                NUMBER(14),                
       DIRECCION               VARCHAR2(50),
       CORREO_ELECTRONICO      VARCHAR2(50),
       CONSTRAINT Proveedor_IdProveedor_pk PRIMARY KEY(ID_PROVEEDOR)
);

CREATE TABLE COMPRA(
	ID_COMPRA		NUMBER(15) NOT NULL,
	ID_PROVEEDOR		NUMBER(10) NOT NULL,
	ID_EMPLEADO		NUMBER(11) NOT NULL,
	FECHA_COMPRA            DATE,
	CONSTRAINT Com_IdCompra_pk PRIMARY KEY (ID_COMPRA),
	CONSTRAINT Com_IdProveedor_fk FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR),
	CONSTRAINT Com_IdEmpleado_fk1 FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO)
);

CREATE TABLE DETALLE_COMPRA(
	ID_DETALLECOMPRA	NUMBER(7) NOT NULL,
	ID_COMPRA		NUMBER(15) NOT NULL,
	CONSTRAINT DetCompra_IdDetCompra_pk PRIMARY KEY (ID_DETALLECOMPRA),
	CONSTRAINT DeteCompra_IdCompra_fk FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA (ID_COMPRA)
);

CREATE TABLE CATEGORIA_PRODUCTO(
	ID_CATEGORIA 		NUMBER(4) NOT NULL,
	CATEGORIA_PRODUCTO	VARCHAR2(50),
	CONSTRAINT CategProducto_IdCateg_pk PRIMARY KEY (ID_CATEGORIA)
);

CREATE TABLE MARCA_PRODUCTO(
	ID_MARCA		NUMBER(4) NOT NULL,
	MARCA_PRODUCTO	        VARCHAR2(50),
	CONSTRAINT MarcaProd_IdMarca_pk PRIMARY KEY (ID_MARCA)
);
CREATE TABLE PRODUCTO(
	ID_PRODUCTO		NUMBER(15) NOT NULL,
	ID_CATEGORIA		NUMBER(4) NOT NULL,
        ID_MARCA		NUMBER(4) NOT NULL,
        NOMBRE_PRODUCTO         VARCHAR2(50),
	CONSTRAINT Prod_IdProducto_pk PRIMARY KEY (ID_PRODUCTO),
	CONSTRAINT Prod_IdTipo_fk FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_PRODUCTO (ID_CATEGORIA),
        CONSTRAINT Prod_IdTipo_fk1 FOREIGN KEY (ID_MARCA) REFERENCES MARCA_PRODUCTO (ID_MARCA)
);

CREATE TABLE ESTADO(
        ID_ESTADO NUMBER(2)     NOT NULL,
        ESTADO_PRODUCTO		VARCHAR2(20),
        CONSTRAINT Estado_IdEstado_pk PRIMARY KEY(ID_ESTADO),
        CONSTRAINT Estado_EstadoProducto_ck1 CHECK (ESTADO_PRODUCTO = 'DISPONIBLE' OR ESTADO_PRODUCTO = 'NO DISPONIBLE')	
);

CREATE TABLE INVENTARIO(
	ID_INVENTARIO		NUMBER(6) NOT NULL,
	ID_DETALLECOMPRA	NUMBER(7) NOT NULL,
        ID_PRODUCTO		NUMBER(15) NOT NULL,
        ID_ESTADO               NUMBER(2)     NOT NULL,
	PRECIO_UNITARIO		NUMBER(10,2),
	FECHA_VENCIMIENTO       DATE, 
	CONSTRAINT Inv_IdInventario_pk PRIMARY KEY (ID_INVENTARIO),
	CONSTRAINT Inv_IdDetCompra_fk FOREIGN KEY (ID_DETALLECOMPRA) REFERENCES DETALLE_COMPRA (ID_DETALLECOMPRA),
	CONSTRAINT Inv_IdProducto_fk1 FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
        CONSTRAINT Inv_IdEstado_fk2 FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

CREATE TABLE DETALLE_FACTURA(
	ID_DETALLE		NUMBER(7) NOT NULL,
	ID_FACTURA		NUMBER(15) NOT NULL,
	ID_INVENTARIO		NUMBER(4) NOT NULL,
CONSTRAINT DetFactura_IdDetalle_pk PRIMARY KEY (ID_DETALLE),
CONSTRAINT DetFactura_IdFactura_fk FOREIGN KEY (ID_FACTURA) REFERENCES ENCABEZADO_FACTURA (ID_FACTURA),
CONSTRAINT DetFactura_IdInvaentario_fk1 FOREIGN KEY (ID_INVENTARIO) REFERENCES INVENTARIO(ID_INVENTARIO)
);
